### ISSUE TITLE
Unable to delete template files

### ISSUE THREAD

**Issue by MariusStuparu** [nodee-apps/cms#3]
After creating some template files for testing, I am unable to delete any file or folder. I get an ["Access denied..."](http://screencast.com/t/LmVM9HxrZ) message (see linked screenshot), but I cannot delete even after loggin out and in again.

**Comment by matusszabo** [comment]
Seems like a bug, what browser do you using ? Chrome on win7 ?
thank you

**Comment by MariusStuparu** [comment]
Chrome Canary (47.0.2497.0) and Firefox (38.2.1), Windows 8.1 x64. I get this error in FF console:

```
DELETE  XHR  [http...]/admin/cms/templates/indexU+FF0Ehtml [HTTP/1.1 403 Forbidden 1ms]
no element found indexU+FF0Ehtml:1:1
```

Guess it's the utf encoding of the dot.

**Comment by molda** [comment]
Same problem here too. Chrome and Microsoft Edge on Win 10 and Chrome on Android.

**Comment by matusszabo** [comment]
Thanks, I will fix it asap.

**Comment by matusszabo** [comment]
@MariusStuparu , @molda it is fixed, please try it.
I forgot to mention graphicsmagick in install instructions, images won't resize without it.

thank you

**Comment by molda** [comment]
@matusszabo New install and I'm still getting "Acces denied..." when trying to delete default templates and "Document or his version not found, try refresh page, please" when clicking on default template or creating new template :(

node running as root: sudo node debug.js
Cms user roles: admin, user

![untitled](https://cloud.githubusercontent.com/assets/3585693/9616007/0033b5c4-50fc-11e5-9688-98dddc82ed09.png)

**Comment by matusszabo** [comment]
@molda , did you replace whole project folder with new one ? If there is file "dependencies", app will load old packages. You need to remove it. Please check if DELETE requests has content-type header set as "application/json" in chrome. If not, try ctrl+F5 to reload all resources, this will reset browser cache.
Let me know if it helps, thank you.

**Comment by molda** [comment]
@matusszabo I created new folder, unziped cms-master.zip and run npm install. There's no dependencies file. The DELETE requests has content-type header set as "Content-Type:application/json;charset=UTF-8". I can't create files inside folders but there's no problem creating files or folders by clicking "+Add root".  I also tried demo1.nowitssimple.com and it doesn't work for me either.

**Comment by matusszabo** [comment]
@molda , I am testing it on Chrome Version 44.0.2403.157, and it works, also on demo1.nowitssimple.com. What browser and OS are you using ? Will setup VM and test it again.

**Comment by molda** [comment]
@matusszabo Chrome 44.0.2403.157 and Microsoft Edge 20.10240.16384.0  on Win 10. I tried it on my Android phone with chrome and another browser with same results. I can't even create new user. The create button is disabled. So this is problem on my end then. Wondering whats wrong.

**Comment by molda** [comment]
@matusszabo is the url suposed to look like /admin/cms/templates/widgets%2FtestU+FF0Ehtml ???

**Comment by molda** [comment]
With a great help of @matusszabo i solved this issue by upgrading and configuring nginx properly.
So it works a treat now. Thanks

**Comment by matusszabo** [comment]
@molda ,you are welcome :)
